In [15]:
import numpy as np
data = np.arange(0, 20).reshape(4,5)

print(data[(data[:, :-1] < 14).all(axis=1)])
data[:, -1]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 4,  9, 14, 19])